### ISSUE TITLE
Break points

### ISSUE THREAD

**Issue by fosterc1** [nachocinalli/adapt-cards#2]
Hello

Could this be amended to reflect the new breakpoints now in the latest FW?

Thanks

**Comment by nachocinalli** [comment]
Hello Caleb, thank you for testing it out. Would you mind giving it another try with version 1.2.0?
I have recently updated the component, and now you have the ability to specify the number of columns based on the screen size.

**Comment by fosterc1** [comment]
Perfect, all working.

Thanks very much
