### ISSUE TITLE
how to style the cards to have good animation

### ISSUE THREAD

**Issue by dymitar** [nachocinalli/adapt-cards#3]
Not a bug, but it would be really helpful if you include Custom CSS example how to make an animation.
Find attached my (not complete) example, extracted from your demo.
The component becomes really nice with the animation.
[cards-custom-css.zip](https://github.com/nachocinalli/adapt-cards/files/12379709/cards-custom-css.zip)

**Comment by nachocinalli** [comment]
Yes, I understand. In all my components, I always try to keep them with the minimum CSS/LESS required  to work, and then I modify the CSS/LESS from the theme itself according to the needs of the course. I like to do it this way to avoid rewriting the style rules too much. Maybe I can add an example in the readme.md similar to https://github.com/nachocinalli/adapt-talk#adding-basic-css-style

**Comment by dymitar** [comment]
Sure, an example in the readme would be perfect

**Comment by nachocinalli** [comment]
[Style example](https://github.com/nachocinalli/adapt-cards#adding-basic-css-style)
Hope this helps!

**Comment by dymitar** [comment]
Perfect. This will save a lot of time to the people using the component.
