### ISSUE TITLE
Failed at become ready

### ISSUE THREAD

**Issue by sebj8** [nachocinalli/adapt-cards#4]
Component don't show up in:
Adapt authoring tool 0.11.3.
Adapt framework 5.40.3.

![Annotation 2024-07-09 124218](https://github.com/nachocinalli/adapt-cards/assets/32302148/f2ae4985-5fce-4268-abe5-d88ae7fddf14)

**Comment by nachocinalli** [comment]
Hello @sebj8, could you check if the adapt-cards component is installed correctly in the AAT? Please verify that all the directories and files that are part of this component are present. Sometimes, the AAT does not import the plugins properly, and a template or another file might be missing, which causes the component not to work.

**Comment by sebj8** [comment]
Thank you @nachocinalli. I copied the files from the repository to `src\components\adapt-card` (although they were already there) and after rebuilding the course it started to work. Thank you!
